package com.omnicore.identity.role.error;

public enum RoleErrorCode {
  ROLE_NOT_FOUND,
  ROLE_ALREADY_EXISTS,
  ROLE_INACTIVE,
  ROLE_ASSIGNED_TO_USERS,
  SYSTEM_ROLE_UPDATE_RESTRICTED,
  SYSTEM_ROLE_DELETE_RESTRICTED,
  INVALID_ROLE_NAME_FORMAT,
  ROLE_DESCRIPTION_TOO_LONG,
  ROLE_PERMISSION_NOT_FOUND,
  ROLE_PERMISSION_INACTIVE,
  DUPLICATE_ROLE_PERMISSION,
  USER_NOT_FOUND,
  USER_INACTIVE,
  DUPLICATE_USER_ROLE
}
