package com.omnicore.identity.permission.error;

public enum PermissionErrorCode {
  PERMISSION_NOT_FOUND,
  PERMISSION_ALREADY_EXISTS,
  PERMISSION_INACTIVE,
  PERMISSION_ALREADY_ACTIVE,
  INVALID_PERMISSION_NAME_FORMAT,
  INVALID_PERMISSION_ACTION,
  SYSTEM_PERMISSION_UPDATE_RESTRICTED,
  SYSTEM_PERMISSION_DELETE_NOT_ALLOWED,
  PERMISSION_ASSIGNED_TO_ROLE,
  PERMISSION_USED_AS_DEPENDENCY,
  VIEW_DELETED_PERMISSION_REQUIRED,
  PERMISSION_SELF_DEPENDENCY_NOT_ALLOWED,
  PERMISSION_CIRCULAR_DEPENDENCY,
  DEPENDENCY_PERMISSION_NOT_FOUND,
  DEPENDENCY_PERMISSION_INACTIVE,
  DUPLICATE_DEPENDENCY_PERMISSION
}
